=== MadeWithLoveInIndia/MadeWithLoveInIndia/public/schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "$id": "https://anandchowdhary.github.io/okrs/schema.json",
  "title": "Made with Love in India project",
  "description": "A project in the collection of Made with Love in India projects",
  "type": "object",
  "properties": {
    "type": {
      "description": "Name",
      "type": "string",
      "enum": [
        "company",
        "open source project",
        "nonprofit",
        "institution",
        "community",
        "personal website",
        "other"
      ]
    },
    "name": {
      "description": "Name",
      "type": "string"
    },
    "tagline": {
      "description": "Description up to 50 characters",
      "type": "string",
      "maxLength": 50
    },
    "url": {
      "description": "Landing page URL",
      "type": "string"
    },

    "description": {
      "description": "Long description in markdown",
      "type": "string"
    },
    "logo": {
      "description": "Hosted logo URL",
      "type": "string"
    },
    "founded": {
      "description": "Year founded",
      "type": "number",
      "minimum": 1947
    },
    "city": {
      "description": "City",
      "type": "string"
    },
    "state": {
      "description": "State",
      "type": "string"
    },

    "blog": {
      "description": "Blog URL",
      "type": "string"
    },
    "github_username": {
      "description": "GitHub username",
      "type": "string"
    },
    "github_repository_name": {
      "description": "GitHub repository name without the username",
      "type": "string"
    },
    "facebook": {
      "description": "Facebook page or profile username",
      "type": "string"
    },
    "twitter": {
      "description": "Twitter username",
      "type": "string"
    },
    "instagram": {
      "description": "Instagram username",
      "type": "string"
    },
    "linkedin_profile": {
      "description": "LinkedIn profile username",
      "type": "string"
    },
    "linkedin_page": {
      "description": "LinkedIn company username or ID",
      "type": "string"
    },

    "adminTags": {
      "description": "Tags",
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": ["type", "name", "tagline", "url", "city", "state"]
}

=== MadeWithLoveInIndia/MadeWithLoveInIndia/data/crew-attendance.json
{
  "$schema": "http://madewithloveinindia.org/schema.json",
  "type": "open source project",
  "name": "Crew Attendance",
  "tagline": "Mark attendance using real-time face recognition",
  "url": "https://github.com/CrewCodeAnku/crew-attendance-nextjs-python-flutter",
  "city": "Mohali",
  "state": "punjab"
}

=== MadeWithLoveInIndia/MadeWithLoveInIndia/data/breast-cancer-detection-app.json
{
  "$schema": "http://madewithloveinindia.org/schema.json",
  "type": "open source project",
  "name": "Breast-Cancer-Detection-App",
  "tagline": "Classify images of breast cells into classes",
  "url": "https://github.com/Harirai/Breast-Cancer-Detection-App",
  "city": "Varanasi",
  "state": "uttar-pradesh"
}

=== MadeWithLoveInIndia/MadeWithLoveInIndia/data/abdullah-amal-khans-portfolio.json
{
  "$schema": "http://madewithloveinindia.org/schema.json",
  "type": "open source project",
  "name": "Abdullah Amal Khan's Portfolio",
  "tagline": "Dynamic personal portfolio showcasing my skills",
  "url": "https://github.com/probablyabdullah/portfolio",
  "city": "Bangalore",
  "state": "karnataka"
}

=== MadeWithLoveInIndia/MadeWithLoveInIndia/data/github-feed-notifier.json
{
  "$schema": "http://madewithloveinindia.org/schema.json",
  "type": "open source project",
  "name": "GitHub Feed Notifier",
  "tagline": "Notification service for GitHub dashboard updates",
  "url": "https://github.com/plibither8/github-feed-notifier",
  "city": "New Delhi",
  "state": "delhi"
}
