=== MadeWithLoveInIndia/MadeWithLoveInIndia/public/schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "$id": "https://anandchowdhary.github.io/okrs/schema.json",
  "title": "Made with Love in India project",
  "description": "A project in the collection of Made with Love in India projects",
  "type": "object",
  "properties": {
    "type": {
      "description": "Name",
      "type": "string",
      "enum": [
        "company",
        "open source project",
        "nonprofit",
        "institution",
        "community",
        "personal website",
        "other"
      ]
    },
    "name": {
      "description": "Name",
      "type": "string"
    },
    "tagline": {
      "description": "Description up to 50 characters",
      "type": "string",
      "maxLength": 50
    },
    "url": {
      "description": "Landing page URL",
      "type": "string"
    },

    "description": {
      "description": "Long description in markdown",
      "type": "string"
    },
    "logo": {
      "description": "Hosted logo URL",
      "type": "string"
    },
    "founded": {
      "description": "Year founded",
      "type": "number",
      "minimum": 1947
    },
    "city": {
      "description": "City",
      "type": "string"
    },
    "state": {
      "description": "State",
      "type": "string"
    },

    "blog": {
      "description": "Blog URL",
      "type": "string"
    },
    "github_username": {
      "description": "GitHub username",
      "type": "string"
    },
    "github_repository_name": {
      "description": "GitHub repository name without the username",
      "type": "string"
    },
    "facebook": {
      "description": "Facebook page or profile username",
      "type": "string"
    },
    "twitter": {
      "description": "Twitter username",
      "type": "string"
    },
    "instagram": {
      "description": "Instagram username",
      "type": "string"
    },
    "linkedin_profile": {
      "description": "LinkedIn profile username",
      "type": "string"
    },
    "linkedin_page": {
      "description": "LinkedIn company username or ID",
      "type": "string"
    },

    "adminTags": {
      "description": "Tags",
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": ["type", "name", "tagline", "url", "city", "state"]
}

=== MadeWithLoveInIndia/MadeWithLoveInIndia/data/stock-market-price-checking-app.json
{
  "$schema": "http://madewithloveinindia.org/schema.json",
  "type": "open source project",
  "name": "Stock Market Price Checking App",
  "tagline": "Real-time stock market price cheking app",
  "url": "https://github.com/chinmayagrawal775/stockmarket-using-django-channels-celery",
  "city": "Mathura",
  "state": "uttar-pradesh"
}

=== MadeWithLoveInIndia/MadeWithLoveInIndia/data/bank-account-simulation.json
{
  "$schema": "http://madewithloveinindia.org/schema.json",
  "type": "open source project",
  "name": "Bank Account Simulation",
  "tagline": "All the basic functions of a bank account",
  "url": "https://github.com/AnshDMishra/Bank-Account-Simulation-",
  "city": "New Delhi",
  "state": "delhi"
}

=== MadeWithLoveInIndia/MadeWithLoveInIndia/data/messaging-app-flutter-firebase.json
{
  "$schema": "http://madewithloveinindia.org/schema.json",
  "type": "open source project",
  "name": "Messaging App - Flutter & Firebase",
  "tagline": "Messaging app build using Flutter and Firebase",
  "url": "https://github.com/AmanNegi/Messaging-App-Flutter-",
  "city": "Dehradun",
  "state": "uttarakhand"
}

=== MadeWithLoveInIndia/MadeWithLoveInIndia/data/d3v-store.json
{
  "$schema": "http://madewithloveinindia.org/schema.json",
  "type": "company",
  "name": "D3V.STORE",
  "tagline": "Debug Your Wardrobe",
  "url": "https://d3v.store",
  "city": "Kanpur",
  "state": "Uttar Pradesh",
  "linkedin_page": "https://www.linkedin.com/company/d3v-store/",
  "founded": 2021,
  "logo": "https://d3v.store/wp-content/uploads/2024/04/cropped-White-Black-M-Letter-Design-Business-Identity-for-Digital-Design-Company-Logo.png"
}

=== MadeWithLoveInIndia/MadeWithLoveInIndia/data/tooloza.json
{
  "$schema": "https://madewithloveinindia.org/schema.json",
  "type": "other",
  "name": "Toolooza",
  "tagline": "Supercharge productivity with 100+ free tools",
  "url": "https://tooloza.com/",
  "logo": "https://tooloza.com/uploads/main/001344fdd72147bfed63a3d6b9c72a7c.png",
  "founded": 2025,
  "city": "Hyderabad",
  "state": "telangana"
}

=== MadeWithLoveInIndia/MadeWithLoveInIndia/data/geek-circuit.json
{
  "$schema": "https://madewithloveinindia.org/schema.json",
  "type": "other",
  "name": "Geek Circuit",
  "tagline": "Tech guides, tips, and tricks for devs!",
  "url": "https://www.geekcircuit.com/",
  "logo": "https://www.geekcircuit.com/wp-content/uploads/2025/04/logo_light.webp",
  "founded": 2024,
  "city": "Hyderabad",
  "state": "telangana"
}

=== MadeWithLoveInIndia/MadeWithLoveInIndia/data/asciinema-player-for-github.json
{
  "$schema": "http://madewithloveinindia.org/schema.json",
  "type": "open source project",
  "name": "asciinema Player for GitHub",
  "tagline": "Embed asciinema links in READMEs on GitHub",
  "url": "https://github.com/plibither8/asciinema-player-for-github",
  "city": "New Delhi",
  "state": "delhi"
}

=== MadeWithLoveInIndia/MadeWithLoveInIndia/data/gyft.json
{
  "$schema": "http://madewithloveinindia.org/schema.json",
  "type": "company",
  "name": "Gyft & Co.",
  "logo": "https://storage.googleapis.com/gyft--app.appspot.com/Logo.png",
  "tagline": "Crafting memories with Love.",
  "url": "https://gyft.app",
  "founded": 2019,
  "city": "Hyderabad",
  "state": "telangana",
  "facebook": "teamgyft",
  "twitter": "gyft_co",
  "instagram": "gyft.co"
}
